name: Run tests

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ]
        versions: [ '8.2', '8.3', '8.4' ]
    name: PHP ${{ matrix.versions }} Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.versions }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pgsql, mysqli pdo_sqlite, pdo_mysql, pdo_pgsql, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
            bun-version: latest

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan migrate
          php artisan db:seed
          bun install
          bun run build

      - name: Run tests
        run: php artisan test
